export const defaultProps = {
  Wrapper: null,
  Input: null,
  IconLeftCon: null,
  IconRightCon: null,
  InputCon: null,
  CloseIconCon: null,
  type: 'text',
  name: 'UNAMEDtextField',
  validation: [],
  font: 'primary',
  color: 'white',
  foregroundColor: 'primary',
  backgroundColor: 'white',
  textColor: 'black',
  round: null,
  IconLeft: null,
  IconRight: null,
  placeholder: null,
  width: 'fit-content',
  label: null,
  autocomplete: 'off',
  defaultValue: '',
  clearOnSubmit: null,
  dataCy: null,
  setInSessionStorage: null,
  onFocus: () => null,
  onBlur: () => null,
  onLeftIconClick: () => null,
  onRightIconClick: () => null,
  onInput: () => null,
}
